apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-backend
  ports:
  - port: 8080
    targetPort: 8080
