apiVersion: v1
kind: Service
metadata:
  name: test-dashboard
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: test-website
  ports:
  - port: 80
    targetPort: 80
