apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka-infra
  namespace: flux-workloads
resources:
- namespace.yaml
- strimzi-crds.yaml
- strimzi-cluster-operator.yaml
