apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/strimzi/strimzi-kafka-operator/releases/download/strimzi-0.50.0/install-cluster-operator.yaml
- namespace.yaml

