apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend
  annotations:
    metallb.universe.tf/address-pool: metallb
spec:
  type: LoadBalancer
  selector:
    app: monitoring-frontend
  ports:
  - port: 80
    targetPort: 80
